# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
#ENV['FORWARD_DOCKER_PORTS'] = 'true'

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.force_host_vm = true
    d.name = "vaultier"
    d.ports = [ "80:80" ]
    d.image = "rclick/vaultier:latest"
    d.vagrant_vagrantfile = "./Vagrantfile.dockerhost"
  end
end
