# -*- mode: ruby -*-
# vi: set ft=ruby :

#ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.require_version ">= 1.7.2"

VAGRANTFILE_API_VERSION = "2"
ENABLE_GUI = false

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #Add the vms to each others host file
  config.hostmanager.enabled = true
  #Add entry to local hosts file
  config.hostmanager.manage_host = true

  #The hostmanager plugin can't determine dhcp addresses under virtualbox
  #https://github.com/smdahlen/vagrant-hostmanager/issues/86
  config.vm.provider "virtualbox" do |vb, override|
    override.hostmanager.ip_resolver = proc do |vm, resolving_vm|
      if vm.id
        `VBoxManage guestproperty get #{vm.id} "/VirtualBox/GuestInfo/Net/1/V4/IP"`.split()[1]
      end
    end
  end

  #Enable the GUI if required.
  config.vm.provider "vmware_workstation" do |v|
    v.gui = ENABLE_GUI 
  end

  config.vm.provider "virtualbox" do |v|
    v.gui = ENABLE_GUI
  end

  #Define Virtual Machines
  config.vm.define "centos7" do |centos7|
    centos7.vm.box = "puppetlabs/centos-7.0-64-nocm"
    centos7.vm.hostname = "centos7.dev.jamie.so"
    centos7.hostmanager.aliases = %w( centos7 )
    centos7.vm.provision "shell", path: "scripts/centos7-setup.sh"
    centos7.vm.synced_folder "bin", "/opt/vex"
    centos7.vm.network "forwarded_port", guest: 80, host: 8080 
    centos7.vm.network "private_network", type: "dhcp"
  end

end
